"""
Apply high-confidence nutrition quality review results.

This script consumes deepseek_review.json generated by
audit_nutrition_quality_deepseek.py. It is intentionally conservative:

- only applies decision=fix/deactivate with confidence >= threshold
- only updates food_nutrition_library rows
- also rewrites matching historical user_food_records/items and
  analysis_tasks.result items when names match exactly
- writes a full before/after report before committing

Usage:
    python backend/scripts/apply_nutrition_quality_review.py \
        --review-json D:/files/downloads/.../deepseek_review.json --dry-run
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from copy import deepcopy
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Sequence

import psycopg2
import yaml
from dotenv import load_dotenv


SUGGESTED_KEYS = ["kcal", "protein", "carbs", "fat", "fiber", "sugar"]


def _backend_dir() -> Path:
    return Path(__file__).resolve().parent.parent


def _load_local_env() -> None:
    backend = _backend_dir()
    load_dotenv(backend / ".env", override=False)
    load_dotenv(backend / ".env.local", override=False)


def _read_config(config_path: Path) -> Dict[str, Any]:
    with config_path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _config_value(config: Dict[str, Any], path: Sequence[str], default: Any = "") -> Any:
    cur: Any = config
    for key in path:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(key)
    return default if cur is None else cur


def _postgres_dsn(config: Dict[str, Any]) -> str:
    host = os.getenv("POSTGRESQL_HOST") or _config_value(config, ["database", "host"])
    port = os.getenv("POSTGRESQL_PORT") or str(_config_value(config, ["database", "port"], 5432))
    db = os.getenv("POSTGRESQL_DATABASE") or _config_value(config, ["database", "name"])
    user = os.getenv("POSTGRESQL_USER") or _config_value(config, ["database", "user"])
    password = os.getenv("POSTGRESQL_PASSWORD") or _config_value(config, ["database", "password"])
    sslmode = os.getenv("POSTGRESQL_SSLMODE") or _config_value(config, ["database", "sslmode"], "disable")
    if not all([host, port, db, user]):
        raise RuntimeError("missing PostgreSQL connection settings")
    return f"host={host} port={port} dbname={db} user={user} password={password} sslmode={sslmode}"


def _f(value: Any) -> float:
    if value is None or value == "":
        return 0.0
    return float(value)


def _round2(value: float) -> float:
    return round(float(value), 4)


def _select_targets(review_path: Path, min_confidence: float) -> List[Dict[str, Any]]:
    rows = json.loads(review_path.read_text(encoding="utf-8"))
    targets = []
    for row in rows:
        decision = row.get("decision")
        confidence = _f(row.get("confidence"))
        if decision not in ("fix", "deactivate") or confidence < min_confidence:
            continue
        if decision == "fix":
            suggested = row.get("suggested") or {}
            missing = [key for key in SUGGESTED_KEYS if key not in suggested or suggested[key] is None]
            if missing:
                raise RuntimeError(f"fix row {row.get('id')} missing suggested keys: {missing}")
        targets.append(row)
    return targets


def _unit_from_target(target: Dict[str, Any]) -> Dict[str, float]:
    suggested = target.get("suggested") or {}
    return {
        "calories": _round2(suggested["kcal"]),
        "protein": _round2(suggested["protein"]),
        "carbs": _round2(suggested["carbs"]),
        "fat": _round2(suggested["fat"]),
        "fiber": _round2(suggested["fiber"]),
        "sugar": _round2(suggested["sugar"]),
    }


def _scaled(unit: Dict[str, float], grams: float) -> Dict[str, float]:
    ratio = max(float(grams), 0.0) / 100.0
    return {key: _round2(value * ratio) for key, value in unit.items()}


def _item_weight(item: Dict[str, Any]) -> float:
    for key in ("intake", "weight", "estimatedWeightGrams", "estimated_weight_grams"):
        try:
            value = float(item.get(key) or 0)
            if value > 0:
                return value
        except Exception:
            continue
    return 100.0


def _patch_item(item: Dict[str, Any], unit: Dict[str, float]) -> bool:
    grams = _item_weight(item)
    nutrients = item.get("nutrients")
    if not isinstance(nutrients, dict):
        nutrients = {}
        item["nutrients"] = nutrients
    scaled = _scaled(unit, grams)
    for key, value in scaled.items():
        nutrients[key] = value
    item["unit_nutrition_per_100g"] = unit
    item["nutrition_source"] = "quality_review_fix"
    return True


def _patch_result_items(result: Dict[str, Any], name_to_unit: Dict[str, Dict[str, float]]) -> bool:
    items = result.get("items")
    if not isinstance(items, list):
        return False
    changed = False
    for item in items:
        if not isinstance(item, dict):
            continue
        name = str(item.get("name") or "")
        unit = name_to_unit.get(name)
        if unit:
            changed = _patch_item(item, unit) or changed
    return changed


def _load_library_rows(conn: Any, ids: Sequence[str]) -> Dict[str, Dict[str, Any]]:
    if not ids:
        return {}
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id::text, canonical_name, kcal_per_100g, protein_per_100g,
                   carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g,
                   is_active, source
            FROM public.food_nutrition_library
            WHERE id::text = ANY(%s)
            """,
            (list(ids),),
        )
        rows = {}
        for row in cur.fetchall():
            rows[row[0]] = {
                "id": row[0],
                "canonical_name": row[1],
                "kcal_per_100g": _f(row[2]),
                "protein_per_100g": _f(row[3]),
                "carbs_per_100g": _f(row[4]),
                "fat_per_100g": _f(row[5]),
                "fiber_per_100g": _f(row[6]),
                "sugar_per_100g": _f(row[7]),
                "is_active": bool(row[8]),
                "source": row[9],
            }
        return rows


def apply_targets(conn: Any, targets: Sequence[Dict[str, Any]], dry_run: bool, out_dir: Path) -> Dict[str, Any]:
    ids = [str(target["id"]) for target in targets]
    before = _load_library_rows(conn, ids)
    name_to_unit: Dict[str, Dict[str, float]] = {}
    applied = []
    skipped = []

    with conn.cursor() as cur:
        for target in targets:
            target_id = str(target["id"])
            existing = before.get(target_id)
            if not existing:
                skipped.append({"id": target_id, "reason": "library row not found"})
                continue
            decision = target.get("decision")
            if decision == "deactivate":
                applied.append(
                    {
                        "id": target_id,
                        "canonical_name": existing["canonical_name"],
                        "decision": "deactivate",
                        "confidence": target.get("confidence"),
                        "reason": target.get("reason"),
                        "before": existing,
                    }
                )
                if not dry_run:
                    cur.execute(
                        """
                        UPDATE public.food_nutrition_library
                        SET is_active = false, updated_at = NOW()
                        WHERE id::text = %s
                        """,
                        (target_id,),
                    )
                continue

            unit = _unit_from_target(target)
            name_to_unit[existing["canonical_name"]] = unit
            after = dict(existing)
            after.update(
                {
                    "kcal_per_100g": unit["calories"],
                    "protein_per_100g": unit["protein"],
                    "carbs_per_100g": unit["carbs"],
                    "fat_per_100g": unit["fat"],
                    "fiber_per_100g": unit["fiber"],
                    "sugar_per_100g": unit["sugar"],
                }
            )
            applied.append(
                {
                    "id": target_id,
                    "canonical_name": existing["canonical_name"],
                    "decision": "fix",
                    "confidence": target.get("confidence"),
                    "reason": target.get("reason"),
                    "before": existing,
                    "after": after,
                }
            )
            if not dry_run:
                cur.execute(
                    """
                    UPDATE public.food_nutrition_library
                    SET kcal_per_100g = %s,
                        protein_per_100g = %s,
                        carbs_per_100g = %s,
                        fat_per_100g = %s,
                        fiber_per_100g = %s,
                        sugar_per_100g = %s,
                        updated_at = NOW()
                    WHERE id::text = %s
                    """,
                    (
                        unit["calories"],
                        unit["protein"],
                        unit["carbs"],
                        unit["fat"],
                        unit["fiber"],
                        unit["sugar"],
                        target_id,
                    ),
                )

        historical_records = []
        historical_tasks = []
        if name_to_unit:
            names = list(name_to_unit.keys())
            cur.execute(
                """
                SELECT id::text, items
                FROM public.user_food_records
                WHERE EXISTS (
                    SELECT 1
                    FROM jsonb_to_recordset(items::jsonb) AS x(name text)
                    WHERE x.name = ANY(%s)
                )
                """,
                (names,),
            )
            for record_id, items in cur.fetchall():
                old_items = deepcopy(items)
                new_items = deepcopy(items)
                changed = False
                if isinstance(new_items, list):
                    for item in new_items:
                        if isinstance(item, dict) and str(item.get("name") or "") in name_to_unit:
                            changed = _patch_item(item, name_to_unit[str(item.get("name") or "")]) or changed
                if changed:
                    historical_records.append({"id": record_id, "before": old_items, "after": new_items})
                    if not dry_run:
                        cur.execute(
                            "UPDATE public.user_food_records SET items = %s::jsonb WHERE id::text = %s",
                            (json.dumps(new_items, ensure_ascii=False), record_id),
                        )

            cur.execute(
                """
                SELECT id::text, result
                FROM public.analysis_tasks
                WHERE result IS NOT NULL
                  AND jsonb_typeof(result::jsonb -> 'items') = 'array'
                  AND EXISTS (
                    SELECT 1
                    FROM jsonb_to_recordset(result::jsonb -> 'items') AS x(name text)
                    WHERE x.name = ANY(%s)
                  )
                """,
                (names,),
            )
            for task_id, result in cur.fetchall():
                old_result = deepcopy(result)
                new_result = deepcopy(result)
                if isinstance(new_result, dict) and _patch_result_items(new_result, name_to_unit):
                    historical_tasks.append({"id": task_id, "before": old_result, "after": new_result})
                    if not dry_run:
                        cur.execute(
                            "UPDATE public.analysis_tasks SET result = %s::jsonb WHERE id::text = %s",
                            (json.dumps(new_result, ensure_ascii=False), task_id),
                        )

    report = {
        "generated_at": datetime.now().isoformat(),
        "dry_run": dry_run,
        "target_count": len(targets),
        "applied_count": len(applied),
        "skipped": skipped,
        "applied": applied,
        "historical_user_food_records": {
            "count": len(historical_records),
            "rows": historical_records,
        },
        "historical_analysis_tasks": {
            "count": len(historical_tasks),
            "rows": historical_tasks,
        },
    }
    out_dir.mkdir(parents=True, exist_ok=True)
    suffix = "dry_run" if dry_run else "applied"
    report_path = out_dir / f"nutrition_quality_apply_{suffix}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
    report["report_path"] = str(report_path)
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply high-confidence DeepSeek nutrition quality review.")
    parser.add_argument("--review-json", required=True)
    parser.add_argument("--config", default=str(_backend_dir() / "config.yaml"))
    parser.add_argument("--out-dir", default="D:/files/downloads")
    parser.add_argument("--min-confidence", type=float, default=0.9)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    _load_local_env()
    config = _read_config(Path(args.config))
    targets = _select_targets(Path(args.review_json), args.min_confidence)
    print(f"Selected targets: {len(targets)}")

    conn = psycopg2.connect(_postgres_dsn(config))
    conn.autocommit = False
    try:
        report = apply_targets(conn, targets, args.dry_run, Path(args.out_dir))
        if args.dry_run:
            conn.rollback()
            print("Dry-run complete. Rolled back.")
        else:
            conn.commit()
            print("Applied and committed.")
        print(
            json.dumps(
                {
                    "target_count": report["target_count"],
                    "applied_count": report["applied_count"],
                    "skipped_count": len(report["skipped"]),
                    "historical_user_food_records": report["historical_user_food_records"]["count"],
                    "historical_analysis_tasks": report["historical_analysis_tasks"]["count"],
                    "report_path": report["report_path"],
                },
                ensure_ascii=False,
                indent=2,
            )
        )
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
