#!/usr/bin/env python3
"""Generate Chinese universities seed data."""
import json
import os

universities = [
    # 985
    {"name": "北京大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "清华大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "中国人民大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "北京航空航天大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "北京理工大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "北京师范大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "中国农业大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "中央民族大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "复旦大学", "province": "上海市", "city": "上海市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "上海交通大学", "province": "上海市", "city": "上海市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "同济大学", "province": "上海市", "city": "上海市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "华东师范大学", "province": "上海市", "city": "上海市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "南京大学", "province": "江苏省", "city": "南京市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "东南大学", "province": "江苏省", "city": "南京市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "浙江大学", "province": "浙江省", "city": "杭州市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "中国科学技术大学", "province": "安徽省", "city": "合肥市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "厦门大学", "province": "福建省", "city": "厦门市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "山东大学", "province": "山东省", "city": "济南市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "中国海洋大学", "province": "山东省", "city": "青岛市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "武汉大学", "province": "湖北省", "city": "武汉市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "华中科技大学", "province": "湖北省", "city": "武汉市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "中南大学", "province": "湖南省", "city": "长沙市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "湖南大学", "province": "湖南省", "city": "长沙市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "国防科技大学", "province": "湖南省", "city": "长沙市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "中山大学", "province": "广东省", "city": "广州市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "华南理工大学", "province": "广东省", "city": "广州市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "四川大学", "province": "四川省", "city": "成都市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "电子科技大学", "province": "四川省", "city": "成都市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "重庆大学", "province": "重庆市", "city": "重庆市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "西安交通大学", "province": "陕西省", "city": "西安市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "西北工业大学", "province": "陕西省", "city": "西安市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "西北农林科技大学", "province": "陕西省", "city": "咸阳市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "兰州大学", "province": "甘肃省", "city": "兰州市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "哈尔滨工业大学", "province": "黑龙江省", "city": "哈尔滨市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "吉林大学", "province": "吉林省", "city": "长春市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "东北大学", "province": "辽宁省", "city": "沈阳市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "大连理工大学", "province": "辽宁省", "city": "大连市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "南开大学", "province": "天津市", "city": "天津市", "level": "本科", "is_985": True, "is_211": True},
    {"name": "天津大学", "province": "天津市", "city": "天津市", "level": "本科", "is_985": True, "is_211": True},
    # 211
    {"name": "北京交通大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "北京工业大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "北京科技大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "北京化工大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "北京邮电大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "北京林业大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "北京中医药大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "北京外国语大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中国传媒大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中央财经大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "对外经济贸易大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中国政法大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "华北电力大学", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中国矿业大学（北京）", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中国石油大学（北京）", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中国地质大学（北京）", "province": "北京市", "city": "北京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "上海财经大学", "province": "上海市", "city": "上海市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "上海外国语大学", "province": "上海市", "city": "上海市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "华东理工大学", "province": "上海市", "city": "上海市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "东华大学", "province": "上海市", "city": "上海市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "上海大学", "province": "上海市", "city": "上海市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "海军军医大学", "province": "上海市", "city": "上海市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "苏州大学", "province": "江苏省", "city": "苏州市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "南京航空航天大学", "province": "江苏省", "city": "南京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "南京理工大学", "province": "江苏省", "city": "南京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中国矿业大学", "province": "江苏省", "city": "徐州市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "河海大学", "province": "江苏省", "city": "南京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "江南大学", "province": "江苏省", "city": "无锡市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "南京农业大学", "province": "江苏省", "city": "南京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中国药科大学", "province": "江苏省", "city": "南京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "南京师范大学", "province": "江苏省", "city": "南京市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "暨南大学", "province": "广东省", "city": "广州市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "华南师范大学", "province": "广东省", "city": "广州市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "西南交通大学", "province": "四川省", "city": "成都市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "西南财经大学", "province": "四川省", "city": "成都市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "四川农业大学", "province": "四川省", "city": "雅安市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "西安电子科技大学", "province": "陕西省", "city": "西安市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "长安大学", "province": "陕西省", "city": "西安市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "西北大学", "province": "陕西省", "city": "西安市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "陕西师范大学", "province": "陕西省", "city": "西安市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "空军军医大学", "province": "陕西省", "city": "西安市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "武汉理工大学", "province": "湖北省", "city": "武汉市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中国地质大学（武汉）", "province": "湖北省", "city": "武汉市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "华中农业大学", "province": "湖北省", "city": "武汉市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "华中师范大学", "province": "湖北省", "city": "武汉市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中南财经政法大学", "province": "湖北省", "city": "武汉市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "湖南师范大学", "province": "湖南省", "city": "长沙市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "东北师范大学", "province": "吉林省", "city": "长春市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "延边大学", "province": "吉林省", "city": "延边朝鲜族自治州", "level": "本科", "is_985": False, "is_211": True},
    {"name": "辽宁大学", "province": "辽宁省", "city": "沈阳市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "大连海事大学", "province": "辽宁省", "city": "大连市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "东北林业大学", "province": "黑龙江省", "city": "哈尔滨市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "东北农业大学", "province": "黑龙江省", "city": "哈尔滨市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "太原理工大学", "province": "山西省", "city": "太原市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "内蒙古大学", "province": "内蒙古自治区", "city": "呼和浩特市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "河北工业大学", "province": "天津市", "city": "天津市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "天津医科大学", "province": "天津市", "city": "天津市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "合肥工业大学", "province": "安徽省", "city": "合肥市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "安徽大学", "province": "安徽省", "city": "合肥市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "福州大学", "province": "福建省", "city": "福州市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "南昌大学", "province": "江西省", "city": "南昌市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "中国石油大学（华东）", "province": "山东省", "city": "青岛市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "广西大学", "province": "广西壮族自治区", "city": "南宁市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "海南大学", "province": "海南省", "city": "海口市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "贵州大学", "province": "贵州省", "city": "贵阳市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "云南大学", "province": "云南省", "city": "昆明市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "西藏大学", "province": "西藏自治区", "city": "拉萨市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "青海大学", "province": "青海省", "city": "西宁市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "宁夏大学", "province": "宁夏回族自治区", "city": "银川市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "新疆大学", "province": "新疆维吾尔自治区", "city": "乌鲁木齐市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "石河子大学", "province": "新疆维吾尔自治区", "city": "石河子市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "郑州大学", "province": "河南省", "city": "郑州市", "level": "本科", "is_985": False, "is_211": True},
    {"name": "哈尔滨工程大学", "province": "黑龙江省", "city": "哈尔滨市", "level": "本科", "is_985": False, "is_211": True},
    # Key provincial universities
    {"name": "深圳大学", "province": "广东省", "city": "深圳市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "南方科技大学", "province": "广东省", "city": "深圳市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "浙江工业大学", "province": "浙江省", "city": "杭州市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "宁波大学", "province": "浙江省", "city": "宁波市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "杭州电子科技大学", "province": "浙江省", "city": "杭州市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "昆明理工大学", "province": "云南省", "city": "昆明市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "西安理工大学", "province": "陕西省", "city": "西安市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "成都理工大学", "province": "四川省", "city": "成都市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "重庆邮电大学", "province": "重庆市", "city": "重庆市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "湘潭大学", "province": "湖南省", "city": "湘潭市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "青岛大学", "province": "山东省", "city": "青岛市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "河南大学", "province": "河南省", "city": "开封市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "河北大学", "province": "河北省", "city": "保定市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "燕山大学", "province": "河北省", "city": "秦皇岛市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "山西大学", "province": "山西省", "city": "太原市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "黑龙江大学", "province": "黑龙江省", "city": "哈尔滨市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "长春理工大学", "province": "吉林省", "city": "长春市", "level": "本科", "is_985": False, "is_211": False},
    {"name": "辽宁工程技术大学", "province": "辽宁省", "city": "阜新市", "level": "本科", "is_985": False, "is_211": False},
]

if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "..", "data", "schools_seed.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        json.dump(universities, f, ensure_ascii=False, indent=2)
    print(f"Generated {len(universities)} universities to {out}")
