import { act, fireEvent, render, screen } from '@testing-library/react'
import Taro from '@tarojs/taro'
import { PetExploreGame } from '../../src/packagePetStudio/components/PetExploreGame'
import type { PetProfile } from '../../src/utils/api'

jest.mock('../../src/components/PetActor', () => ({ PetActor: ({ pet, action }: { pet: PetProfile; action: string }) => <span data-testid='explore-pet' data-action={action}>{pet.name}</span> }))
const pet = { id: 'original-pet', name: '鬼鬼' } as PetProfile
const props = { active: true, pet, accountId: 'account-one', onFinished: jest.fn(), onExit: jest.fn() }

beforeEach(() => { jest.clearAllMocks(); jest.useFakeTimers(); jest.setSystemTime(new Date('2026-10-02T00:00:00Z')) })
afterEach(() => jest.useRealTimers())
function click(container: HTMLElement, id: string) { const el = container.querySelector(`#${id}`); expect(el).not.toBeNull(); fireEvent.click(el as Element) }
function wait(ms: number) { act(() => { jest.advanceTimersByTime(ms) }) }
async function flush() { await act(async () => { await Promise.resolve(); await Promise.resolve() }) }
function toHaul(container: HTMLElement) {
  click(container, 'explore-start')
  click(container, 'explore-node-clue')
  click(container, 'explore-observe')
  click(container, 'explore-node-canal')
  click(container, 'explore-challenge')
  for (const [index, count] of [[0, 3], [1, 2], [2, 3]]) for (let turn = 0; turn < count; turn += 1) click(container, `explore-canal-${index}`)
  click(container, 'explore-check-canal')
  click(container, 'explore-node-pebble')
  click(container, 'explore-challenge')
}
function haul(container: HTMLElement) {
  click(container, 'explore-pull-toggle')
  for (let step = 0; step < 200 && container.querySelector('#explore-haul'); step += 1) {
    const panel = container.querySelector('#explore-haul')!
    const tension = Number(panel.getAttribute('data-tension'))
    const pulling = panel.getAttribute('data-pulling') === 'true'
    if (pulling && tension >= 55 || !pulling && tension <= 30) click(container, 'explore-pull-toggle')
    wait(100)
  }
  expect(container.querySelector('#explore-haul')).toBeNull()
}

test('a real route, water rotations and accessible reel controls produce an actual result with the original pet', async () => {
  const callback = jest.fn()
  const replacement = jest.fn()
  const { container, rerender } = render(<PetExploreGame {...props} onFinished={callback} />)
  expect(screen.getByTestId('explore-pet')).toHaveTextContent('鬼鬼')
  toHaul(container)
  rerender(<PetExploreGame {...props} onFinished={replacement} />)
  haul(container)
  click(container, 'explore-finish')
  await flush()
  expect(container.querySelector('#explore-result')).toHaveAttribute('data-score', '400')
  expect(callback).toHaveBeenCalledTimes(1)
  expect(callback).toHaveBeenCalledWith(expect.objectContaining({ game: 'explore', levelId: 1, completed: true, stars: 3, collectibles: ['pebble-ornament', 'waterside-memory-1'] }), expect.stringMatching(/^explore:/), 'account-one')
  expect(replacement).not.toHaveBeenCalled()
  wait(10000)
  expect(callback).toHaveBeenCalledTimes(1)
  expect(Taro.setStorageSync).not.toHaveBeenCalled()
})

test('deactivating or hiding the page freezes hauling and requires explicit resume', () => {
  const { container, rerender } = render(<PetExploreGame {...props} />)
  toHaul(container)
  click(container, 'explore-pull-toggle')
  wait(1000)
  const before = container.querySelector('#explore-haul')?.getAttribute('data-progress')
  rerender(<PetExploreGame {...props} active={false} />)
  wait(5000)
  expect(container.querySelector('#explore-haul')).toHaveAttribute('data-progress', before)
  expect(container.querySelector('#explore-resume')).toBeDisabled()
  expect(container.querySelector('#explore-back')).toBeDisabled()
  expect(container.querySelector('#explore-paused-exit')).toBeDisabled()
  rerender(<PetExploreGame {...props} />)
  expect(container.querySelector('#explore-world')).toHaveAttribute('data-state', 'paused')
  click(container, 'explore-resume')
  expect(container.querySelector('#explore-haul')).toHaveAttribute('data-pulling', 'false')
  click(container, 'explore-pull-toggle')
  const hide = (Taro.useDidHide as jest.Mock).mock.calls.slice(-1)[0][0]
  act(() => hide())
  expect(container.querySelector('#explore-world')).toHaveAttribute('data-state', 'paused')
  wait(5000)
  expect(container.querySelector('#explore-haul')).toHaveAttribute('data-progress', before)
})

test.each(['account', 'pet'])('switching %s stops the old journey without invoking its settlement', async change => {
  const callback = jest.fn()
  const { container, rerender } = render(<PetExploreGame {...props} onFinished={callback} />)
  toHaul(container)
  click(container, 'explore-pull-toggle')
  wait(1000)
  rerender(<PetExploreGame {...props} accountId={change === 'account' ? 'account-two' : 'account-one'} pet={change === 'pet' ? { ...pet, id: 'other-pet', name: '小麦' } : pet} onFinished={callback} />)
  wait(30000)
  await flush()
  expect(container.querySelector('#explore-start')).toBeInTheDocument()
  expect(container.querySelector('#explore-world')).toHaveAttribute('data-state', 'ready')
  expect(callback).not.toHaveBeenCalled()
})

test('save failure blocks all new-trip and exit controls and retry does not repeat onFinished', async () => {
  const callback = jest.fn()
  const retry = jest.fn()
  const exit = jest.fn()
  const { container, rerender } = render(<PetExploreGame {...props} onFinished={callback} onExit={exit} />)
  click(container, 'explore-start')
  click(container, 'explore-node-clue')
  click(container, 'explore-observe')
  click(container, 'explore-finish')
  await flush()
  rerender(<PetExploreGame {...props} onFinished={callback} onExit={exit} settlementText='收获未保存' onRetrySettlement={retry} />)
  expect(container.querySelector('#explore-continue')).toBeDisabled()
  expect(container.querySelector('#explore-result-exit')).toBeDisabled()
  expect(container.querySelector('#explore-back')).toBeDisabled()
  click(container, 'explore-retry-settlement')
  await flush()
  expect(retry).toHaveBeenCalledTimes(1)
  expect(callback).toHaveBeenCalledTimes(1)
  expect(exit).not.toHaveBeenCalled()
  rerender(<PetExploreGame {...props} onFinished={callback} onExit={exit} settlementText='收获已保存' />)
  expect(container.querySelector('#explore-continue')).not.toBeDisabled()
  click(container, 'explore-continue')
  expect(container.querySelector('#explore-world')).toHaveAttribute('data-score', '0')
  click(container, 'explore-node-clue')
  click(container, 'explore-observe')
  expect(container.querySelector('#explore-world')).toHaveAttribute('data-score', '0')
})

test('leaving during preparation or a paused unfinished journey produces no result', () => {
  const callback = jest.fn()
  const exit = jest.fn()
  const { container } = render(<PetExploreGame {...props} onFinished={callback} onExit={exit} />)
  click(container, 'explore-back')
  expect(callback).not.toHaveBeenCalled()
  click(container, 'explore-start')
  click(container, 'explore-node-clue')
  click(container, 'explore-back')
  click(container, 'explore-paused-exit')
  expect(exit).toHaveBeenCalledTimes(2)
  expect(callback).not.toHaveBeenCalled()
})

test('an account switch before the settlement microtask prevents sending the old round to either account', async () => {
  const callback = jest.fn()
  const { container, rerender } = render(<PetExploreGame {...props} onFinished={callback} />)
  click(container, 'explore-start')
  click(container, 'explore-node-clue')
  click(container, 'explore-observe')
  click(container, 'explore-finish')
  rerender(<PetExploreGame {...props} accountId='account-two' onFinished={callback} />)
  await flush()
  expect(callback).not.toHaveBeenCalled()
  expect(container.querySelector('#explore-world')).toHaveAttribute('data-state', 'ready')
})

test('a thrown settlement remains blocked until its dedicated retry succeeds without replaying finish', async () => {
  const callback = jest.fn().mockRejectedValue(new Error('offline'))
  const retry = jest.fn().mockResolvedValue(undefined)
  const { container, rerender } = render(<PetExploreGame {...props} onFinished={callback} />)
  click(container, 'explore-start')
  click(container, 'explore-node-clue')
  click(container, 'explore-observe')
  click(container, 'explore-finish')
  await flush()
  expect(container.querySelector('#explore-continue')).toBeDisabled()
  expect(container.querySelector('#explore-result-exit')).toBeDisabled()
  expect(screen.getByText('收获未保存，请重试保存后再离开。')).toBeInTheDocument()
  rerender(<PetExploreGame {...props} onFinished={callback} onRetrySettlement={retry} />)
  click(container, 'explore-retry-settlement')
  await flush()
  rerender(<PetExploreGame {...props} onFinished={callback} settlementText='已保存' />)
  expect(container.querySelector('#explore-continue')).not.toBeDisabled()
  expect(callback).toHaveBeenCalledTimes(1)
  expect(retry).toHaveBeenCalledTimes(1)
})

test('a local callback failure can retry the captured result and same round even without a parent retry handler', async () => {
  const callback = jest.fn().mockRejectedValueOnce(new Error('offline')).mockResolvedValue(undefined)
  const { container } = render(<PetExploreGame {...props} onFinished={callback} />)
  click(container, 'explore-start')
  click(container, 'explore-node-clue')
  click(container, 'explore-observe')
  click(container, 'explore-finish')
  await flush()
  expect(container.querySelector('#explore-continue')).toBeDisabled()
  expect(container.querySelector('#explore-result-exit')).toBeDisabled()
  expect(container.querySelector('#explore-retry-settlement')).not.toBeDisabled()
  click(container, 'explore-retry-settlement')
  await flush()
  expect(callback).toHaveBeenCalledTimes(2)
  expect(callback.mock.calls[1]).toEqual(callback.mock.calls[0])
  expect(container.querySelector('#explore-continue')).not.toBeDisabled()
})

test('the four-piece canal labels its real right-side outlet rather than a misleading top exit', () => {
  const { container } = render(<PetExploreGame {...props} startLevel={3} />)
  click(container, 'explore-start')
  click(container, 'explore-node-bridge')
  click(container, 'explore-node-clue')
  click(container, 'explore-observe')
  click(container, 'explore-node-east-canal')
  click(container, 'explore-challenge')
  expect(screen.getByText('出口 →')).toBeInTheDocument()
  expect(screen.queryByText('↑ 出口')).not.toBeInTheDocument()
})

test('unmounting a live haul clears its timers and never settles that abandoned round', async () => {
  const callback = jest.fn()
  const { container, unmount } = render(<PetExploreGame {...props} onFinished={callback} />)
  toHaul(container)
  click(container, 'explore-pull-toggle')
  wait(1000)
  expect(jest.getTimerCount()).toBeGreaterThan(0)
  unmount()
  expect(jest.getTimerCount()).toBe(0)
  wait(120000)
  await flush()
  expect(callback).not.toHaveBeenCalled()
})

test('budget exhaustion after a discovered clue settles the real failed trip once and keeps its clue on continuation', async () => {
  const callback = jest.fn()
  const { container } = render(<PetExploreGame {...props} onFinished={callback} />)
  click(container, 'explore-start')
  click(container, 'explore-node-clue')
  click(container, 'explore-observe')
  for (const id of ['camp', 'lookout', 'camp', 'lookout', 'camp', 'lookout', 'camp']) click(container, `explore-node-${id}`)
  await flush()
  expect(callback).toHaveBeenCalledTimes(1)
  expect(callback).toHaveBeenCalledWith(expect.objectContaining({ completed: false, score: 50, stars: 0, detail: expect.objectContaining({ moves: 8, nodes: 1, remaining: 0 }) }), expect.any(String), 'account-one')
  click(container, 'explore-continue')
  expect(container.querySelector('#explore-world')).toHaveAttribute('data-remaining', '8')
  expect(screen.getByText(/1\. 浅滩石牌/)).toBeInTheDocument()
  click(container, 'explore-node-clue')
  click(container, 'explore-observe')
  expect(container.querySelector('#explore-world')).toHaveAttribute('data-score', '0')
})
